version: '2'
services:
  app:
    container_name: 'lumen'
    build:
      context: .
    volumes:
      - ./:/var/www
    ports:
      - '8080:80'
  web:
    container_name: 'nginx'
    build:
      context: ./nginx
    ports:
      - '80:80'
      - '443:443'
  redis:
    image: redis:3
    container_name: 'redis'
    ports:
      - '6379:6379'
  database:
    image: mysql:5.7.17
    container_name: 'mysql'
    ports:
      - '3306:3306'
    environment:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_DATABASE: homestead
      DB_USERNAME: homestead
      DB_PASSWORD: secret
    volumes:
      - ./:/var/lib/mysql
